services:
  - type: web
    name: finance-web-app
    env: docker
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
